name: Build docker images

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build.yml'
    - 'create_bootstrap_archlinux.sh'
    - 'arm_gcc.sh'
    - 'aarch64_gcc.sh'
    - 'i686_binutils.sh'
    - 'Dockerfile'
  pull_request:
    paths:
    - '.github/workflows/build.yml'
    - 'create_bootstrap_archlinux.sh'
    - 'arm_gcc.sh'
    - 'aarch64_gcc.sh'
    - 'i686_binutils.sh'
    - 'Dockerfile'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get bootstrap
      run: ./create_bootstrap_archlinux.sh "x86_64"
    - name: Build images docker
      run: |
        cat "archlinux-x86_64.tar.gz" | docker import --platform "linux/amd64" - archlinux-builder:bootstrap
        docker build --platform="linux/amd64" -t "ghcr.io/termux-pacman/archlinux-builder:latest" .
        docker save --output archlinux-builder-x86_64.tar "ghcr.io/termux-pacman/archlinux-builder:latest"
    - uses: actions/upload-artifact@v4
      with:
        name: archlinux-builder-x86_64
        path: archlinux-builder-x86_64.tar
        if-no-files-found: error
  push:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get docker images
      uses: actions/download-artifact@v4
      with:
        name: archlinux-builder-x86_64
        path: ./
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push docker images
      run: |
        docker load < archlinux-builder-x86_64.tar
        docker push ghcr.io/termux-pacman/archlinux-builder:latest
